rule report:
    input:
        event_selection_summary=EVENT_SELECTION_SUMMARY,
        event_selection_validation=EVENT_SELECTION_VALIDATION,
        categorization_summary=CATEGORIZATION_SUMMARY,
        categorization_validation=CATEGORIZATION_VALIDATION,
        statistics_summary=STATISTICS_SUMMARY,
        statistics_validation=STATISTICS_VALIDATION,
        plotting_summary=PLOT_SUMMARY,
        workflow_summary=WORKFLOW_SUMMARY,
        workflow_validation=WORKFLOW_VALIDATION,
        region_table=REGION_TABLE,
        region_yield_table=REGION_YIELD_TABLE,
        region_plot_pdf=REGION_PLOT_PDF,
        region_plot_png=REGION_PLOT_PNG
    output:
        report=REPORT
    log:
        f"{WORK_DIR}/logs/report.log"
    conda:
        "../envs/analysis.yaml"
    script:
        "../scripts/report.py"
